docker file verification removed

diff --git a/.github/workflows/mainpipeline.yml b/.github/workflows/mainpipeline.yml
--- a/.github/workflows/mainpipeline.yml
+++ b/.github/workflows/mainpipeline.yml
@@ -52,12 +52,12 @@ jobs:
         run: |
           echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
-      - name: Verify Dockerfile Exists
-        run: |
-          if [ ! -f "Dockerfile" ]; then
-            echo "❌ ERROR: Dockerfile not found in the repository!"
-            exit 1
-          fi
+      #- name: Verify Dockerfile Exists
+          #run: |
+          #if [ ! -f "Dockerfile" ]; then
+          #echo "❌ ERROR: Dockerfile not found in the repository!"
+          #exit 1
+          #fi
 
       - name: Build and Push Docker Image
         run: |
