build image modifications

diff --git a/.github/workflows/mainpipeline.yml b/.github/workflows/mainpipeline.yml
--- a/.github/workflows/mainpipeline.yml
+++ b/.github/workflows/mainpipeline.yml
@@ -54,6 +54,12 @@ jobs:
         run: |
           IMAGE_NAME=siddamjayachandra/my-app
           TIMESTAMP=$(date +%Y%m%d%H%M%S)
+
+          # Check if Dockerfile exists
+          if [ ! -f Dockerfile ]; then
+            echo "Error: Dockerfile not found!"
+            exit 1
+          fi
           
           docker build -t $IMAGE_NAME:${{ github.sha }} -t $IMAGE_NAME:$TIMESTAMP -t $IMAGE_NAME:latest .
           
@@ -71,14 +77,14 @@ jobs:
           host: ${{ secrets.STAGING_SERVER_IP }}
           username: ${{ secrets.STAGING_SERVER_USER }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
-          script: |
-            IMAGE_NAME=siddamjayachandra/my-app
-            docker pull $IMAGE_NAME:latest
-            
-            # Stop and remove any existing container
-            docker stop my-app || true
-            docker rm my-app || true
-            
-            # Start a new container
-            docker run -d -p 80:80 --name my-app $IMAGE_NAME:latest
+        run: |
+          IMAGE_NAME=siddamjayachandra/my-app
+          docker pull $IMAGE_NAME:latest
+          
+          # Stop and remove any existing container
+          docker stop my-app || true
+          docker rm my-app || true
+          
+          # Start a new container
+          docker run -d -p 80:80 --name my-app $IMAGE_NAME:latest
 
